### ISSUE TITLE
New GPT Submission: Ask Dr. Andrew Huberman

### ISSUE THREAD

**Issue by jyboy** [lxfater/Awesome-GPTs#1]
*Name*: Ask Dr. Andrew Huberman
*Description*: Maximize your productivity, physical and mental health with neuroscience. Trained with all the podcast episodes from Huberman Lab.
*Link*: [chat.openai.com/g/g-1xC65osMP-ask-dr-andrew-huberman](https://chat.openai.com/g/g-1xC65osMP-ask-dr-andrew-huberman)

It's similar to another GPT `HubermanGPT` but can provide science-based insights aligned with Dr. Andrew Huberman's expertise.

**Comment by lxfater** [comment]
OK
